owner: nestdotland
repo: status

sites:
  - name: WEB
    url: https://nest.land/package/std/files/flags/mod.ts
    maxResponseTime: 300

  - name: API
    url: https://x.nest.land/api/package/std/0.75.0
    maxResponseTime: 300

  - name: CDN
    url: https://x.nest.land/std@0.75.0/flags/mod.ts
    maxResponseTime: 1500

  - name: Arweave
    url: https://y2dkomn4abqiffiuvhrfhuqynbu4det55c3uipi4gyvvntorwfoa.arweave.net/xoanMbwAYIKVFKniU9IYaGnBkn3ot0Q9HDYrVs3RsVw/flags/mod.ts
    maxResponseTime: 800

assignees: ["nestdotland/core"]

notifications:
  - type: discord

status-website:
  cname: status.nest.land
  name: Nest Status Page
  logoUrl: https://nest.land/images/nest.land/favicon_light.svg
# themeUrl: /theme.css
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/15 * * * *"
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 0 * * *"
  staticSite: "0 0 * * *"
  updates: "0 0 * * *"
