owner: nestdotland
repo: status

sites:
  - name: WEB
    url: https://nest.land/package/std

  - name: API
    url: https://x.nest.land/api/package/std

  - name: CDN
    url: https://x.nest.land/std@0.75.0/flags/mod.ts

  - name: Arweave
    url: https://y2dkomn4abqiffiuvhrfhuqynbu4det55c3uipi4gyvvntorwfoa.arweave.net/xoanMbwAYIKVFKniU9IYaGnBkn3ot0Q9HDYrVs3RsVw/flags/mod.ts

assignees: ["nestdotland/core"]

notifications:
  - type: discord

status-website:
  cname: status.nest.land
  logoUrl: https://nest.land/images/nest.land/favicon_light.svg
  name: Status Page
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
